server:
  port: 8888

spring:
  # 1. env
  config:
    import: file:.env[.properties]
  jackson:
    time-zone: Asia/Seoul

  # 2. file upload setting
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    encoding:
      charset: utf-8
      force: true

  # 3. DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: root
    password: ${MYSQL_PASSWORD}

  # 4. JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # show_sql: true 인데 false로 바꿨음
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  web:
    error:
      include-exception: true
      include-stacktrace: always
      # development : always, deployment : never

# 5. JWT
jwt:
  secret: ${JWT_SECRET}

# 6. AI API
app:
  ai:
    mistral:
      api-key: ${MISTRAL_API_KEY}
      url: https://api.mistral.ai/v1
      model: mistral-small-latest
    gemini:
      api-key: ${GEMINI_API_KEY}
      url: https://generativelanguage.googleapis.com/v1
