server:
  port: 8888

spring:
  # 1. env
  config:
    import: file:.env[.properties]

  # JSON 직렬화 KST
  jackson:
    time-zone: Asia/Seoul

  # 2. file upload setting
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    encoding:
      charset: utf-8
      force: true

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2

  # 3. DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ⚠️ MYSQL_URL 안에 serverTimezone=Asia/Seoul 필수
    url: ${MYSQL_URL}
    username: root
    password: ${MYSQL_PASSWORD}

  # 4. JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul   # ★ 중요

  web:
    error:
      include-exception: true
      include-stacktrace: always

# 5. JWT
jwt:
  secret: ${JWT_SECRET}

# 6. AI API + 공통 앱 설정
app:
  timezone: Asia/Seoul
  ai:
    mistral:
      api-key: ${MISTRAL_API_KEY}
      url: https://api.mistral.ai/v1
      model: mistral-small-latest
    gemini:
      api-key: ${GEMINI_API_KEY}
      url: https://generativelanguage.googleapis.com/v1
